server:
  port: 8080
spring:
  application:
    name: restful-portal
  #h2用于测试环境
  h2:
    console:
      enabled: true
  datasource:
     driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test_spring_ibatis
     url: jdbc:h2:../restfuldb/booklet-restful
     username: restful
     password: password
     schema: classpath:schema.sql
     data: classpath:data.sql
  messages:
    basename: i18n/messages


     

