DROP TABLE IF EXISTS product_a;
DROP TABLE IF EXISTS product_b;
CREATE TABLE product_a(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150), price INT);
CREATE TABLE product_b(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150), price INT);