DROP TABLE IF EXISTS producta;
DROP TABLE IF EXISTS productb;
CREATE TABLE producta(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150), price INT);
CREATE TABLE productb(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150), price INT);