DROP TABLE IF EXISTS product_a;
DROP TABLE IF EXISTS product_b;
DROP TABLE IF EXISTS users;

CREATE TABLE product_a(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(128), price INT);
CREATE TABLE product_b(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(128), price INT);
CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(128), phone VARCHAR(64), appId VARCHAR(128), appSecret VARCHAR(256), lastToken VARCHAR(256));

